M48
; DRILL file {KiCad 7.0.1} date Mon Jun  5 16:13:46 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-06-05T16:13:46-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X132.22Y-65.585
X137.07Y-65.585
T2
X131.92Y-62.555
X137.37Y-62.555
T0
M30
